-- MySQL Script generated by MySQL Workbench
-- Tue Jan  4 16:51:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blogperso
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `blogperso` ;

-- -----------------------------------------------------
-- Schema blogperso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blogperso` DEFAULT CHARACTER SET utf8 ;
USE `blogperso` ;

-- -----------------------------------------------------
-- Table `blogperso`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogperso`.`User` ;

CREATE TABLE IF NOT EXISTS `blogperso`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(60) NULL,
  `lastName` VARCHAR(45) NULL,
  `firstName` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `phone` VARCHAR(15) NULL,
  `status` TINYINT(1) NULL DEFAULT 0 COMMENT '1  = account enable\n0 = account disable',
  `token` VARCHAR(45) NULL,
  `tokenDate` DATETIME NULL,
  `regitrationDate` DATETIME NULL,
  `lastConnectionDate` DATETIME NULL,
  `userType` ENUM("admin", "member") NULL DEFAULT 'member',
  `cvLink` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `picture` VARCHAR(45) NULL,
  `twitter` VARCHAR(45) NULL,
  `gitHub` VARCHAR(45) NULL,
  `linkedIn` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogperso`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogperso`.`Post` ;

CREATE TABLE IF NOT EXISTS `blogperso`.`Post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dateAddPost` DATETIME NULL,
  `dateModifyPost` DATETIME NULL,
  `title` VARCHAR(40) NULL,
  `chapo` VARCHAR(255) NULL,
  `slug` VARCHAR(255) NULL,
  `content` LONGTEXT NULL,
  `picture` VARCHAR(45) NULL,
  `status` TINYINT(1) NULL DEFAULT 0 COMMENT '1 = Post enable\n0 = Post disable\n2 = Post archived',
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Post_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Post_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `blogperso`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogperso`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogperso`.`Comment` ;

CREATE TABLE IF NOT EXISTS `blogperso`.`Comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datePublishComment` DATETIME NULL,
  `dateAddComment` DATETIME NULL,
  `content` LONGTEXT NULL,
  `status` TINYINT(1) NULL DEFAULT 0 COMMENT '1 = comment enable\n2 = comment disable\n0 = comment pending',
  `parentId` INT NULL DEFAULT 0,
  `User_id` INT NOT NULL,
  `Post_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comment_User_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Comment_Post1_idx` (`Post_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `blogperso`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Post1`
    FOREIGN KEY (`Post_id`)
    REFERENCES `blogperso`.`Post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogperso`.`PostCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogperso`.`PostCategory` ;

CREATE TABLE IF NOT EXISTS `blogperso`.`PostCategory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogperso`.`Post_PostCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogperso`.`Post_PostCategory` ;

CREATE TABLE IF NOT EXISTS `blogperso`.`Post_PostCategory` (
  `Post_id` INT NOT NULL,
  `PostCategory_id` INT NOT NULL,
  PRIMARY KEY (`Post_id`, `PostCategory_id`),
  INDEX `fk_Post_has_PostCategory_PostCategory1_idx` (`PostCategory_id` ASC) VISIBLE,
  INDEX `fk_Post_has_PostCategory_Post1_idx` (`Post_id` ASC) VISIBLE,
  CONSTRAINT `fk_Post_has_PostCategory_Post1`
    FOREIGN KEY (`Post_id`)
    REFERENCES `blogperso`.`Post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_has_PostCategory_PostCategory1`
    FOREIGN KEY (`PostCategory_id`)
    REFERENCES `blogperso`.`PostCategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
